Railway_Management /Railway_Management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls'))
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Railway_Management /user/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.Index.as_view()),
    path('create', views.Create.as_view()),  
    path('read',views.Read.as_view()),  
    path('edit/<int:id>', views.Update.as_view()),  
    path('update/<int:id>', views.Update.as_view()),  
    path('delete/<int:id>', views.Delete.as_view()),  
]

Railway_Management /user/models.py
from django.db import models
from django.forms.widgets import Widget



class User(models.Model):
    genderTypes = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
        ('N', 'None')
    )

    id = models.AutoField(db_column='ID',primary_key=True) 
    name = models.CharField(db_column='Name', max_length=30)  
    email = models.EmailField(db_column='Email', max_length=60)
    contact = models.CharField(db_column='Contact_No', max_length=20)
    gender = models.CharField(choices=genderTypes, max_length=10, default="N")
    usrStatus = models.BooleanField(db_column='Maritial Status')
    age = models.IntegerField(db_column='Age')
    date_of_journey = models.DateField(db_column='Date_Of_Journey') 
    seat = models.FloatField(db_column='Seat')
    coach= models.TextField()
    birthmark = models.TextField(db_column='Birthmark')
    usrImg = models.ImageField(db_column='Usr_Img',upload_to='')

    class Meta:
        db_table = 'user'

Railway_Management /user/forms.py
from django import forms  
from .models import User 


class UserForm(forms.ModelForm):
    class Meta:

        usrType = (
            ('True', True),
            ('False', False)
        )
        coachTypes = (
            ('1st AC', '1st AC'),
            ('2nd AC', '2nd AC'),
            ('3rd AC', '3rd AC'),
            ('Sleeper', 'sleeper')
        )

        model = User
        fields = ("id","name","email","contact","gender","usrStatus",'age','date_of_journey', 'seat', 'coach', 'birthmark', 'usrImg')
        widgets = {
        'id':forms.HiddenInput(),
        'name': forms.TextInput(),
        'email': forms.EmailInput(),
        'contact': forms.NumberInput(),
        'usrStatus': forms.RadioSelect(choices=usrType),
        'age': forms.NumberInput(),
        'date_of_journey': forms.DateInput(format=('%d/%m/%Y'), attrs={'class':'form-control', 'placeholder':'Select a date', 'type':'date','required':True}),
        'coach': forms.CheckboxSelectMultiple(choices=coachTypes),
        'birthmark': forms.Textarea(attrs={'rows': 5, 'cols': 30}),
        'usrImg': forms.FileInput(),
        }

Railway_Management /user/views.py
from django.shortcuts import render,redirect
from .forms import UserForm  
from .models import User  
from django.views import View

# Create your views here.  

class Index(View):
    def get(self, request):
        return redirect('/read')

class Create(View):
    def get(self, request):
        form = UserForm()  
        return render(request,'create.html',{'form':form})  

    def post(self, request):
        form = UserForm(request.POST,request.FILES) 
        if form.is_valid():  
            form.save()  
            return redirect('/read')  
            
class Read(View):
    def get(self, request):
        user = User.objects.all()  
        return render(request,"read.html",{'user':user}) 


class Update(View):
    def get(self, request,id):
        user = User.objects.get(id=id)  
        return render(request,'update.html', {'user':user})  

    def post(self,request,id):
        user = User.objects.get(id=id)  
        for i in request.POST:
            if i == 'csrfmiddlewaretoken':
                continue
            if i == 'name':
                if user.name != request.POST['user']:
                    user.name = request.POST['user']
            if i == 'email':
                if user.email != request.POST['email']:
                    user.email = request.POST['email']
            if i == 'contact':
                if user.contact != request.POST['contact']:
                    user.contact = request.POST['contact']
            if i == 'gender':
                if user.gender != request.POST['gender']:
                    user.gender = request.POST['gender']
            if i == 'usrStatus':
                if user.usrStatus != request.POST['usrStatus'] and request.POST['usrStatus'] != '':
                    user.usrStatus = request.POST['usrStatus']
            if i == 'age':
                if user.age != request.POST['age']:
                    user.age = request.POST['age']
            if i == 'date_of_journey':
                if user.date_of_journey != request.POST['date_of_journey'] and request.POST['date_of_journey'] != '':
                    user.date_of_journey = request.POST['date_of_journey']
            if i == 'seat':
                if user.seat != request.POST['seat']:
                    user.seat = request.POST['seat']
            if i == 'birthmark':
                if user.birthmark != request.POST['birthmark']:
                    user.birthmark = request.POST['birthmark']
            if i == 'usrImg':
                if request.POST['usrImg'] != '':
                    user.usrImg = request.FILES['usrImg']
        for i in request.FILES:
            if i == 'usrImg':
                if request.FILES['usrImg'] != '':
                    user.usrImg = request.FILES['usrImg']
        user.save()
        return redirect("/read")  



class Delete(View):
    def get(self,request,id):
        user = User.objects.get(id=id)  
        user.delete()  
        return redirect("/read")      


Railway_Management /templates/create.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Create</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
</head>  
<body style="justify-content: center;">  

<form method="POST" class="post-form" action="/create" enctype="multipart/form-data">  
        {% csrf_token %}  
        <div class="container">  
          <br>  
              <div class="form-group row">  
              <label class="col-sm-1 col-form-label"></label>  
              <div class="col-sm-4">  
              <h3>Details</h3>  
              </div>  
            </div>  
              <div class="form-group row">  
              <label class="col-sm-2 col-form-label">UserId:</label>  
              <div class="col-sm-4">  
                {{ form.id }}  
              </div>  
            </div>  
            <div class="form-group row">  
              <label class="col-sm-2 col-form-label">User Name:</label>  
              <div class="col-sm-4">  
                {{ form.name }}  
              </div>  
            </div>  
              <div class="form-group row">  
              <label class="col-sm-2 col-form-label">User Email:</label>  
              <div class="col-sm-4">  
                {{ form.email }}  
              </div>  
            </div>  
              <div class="form-group row">  
              <label class="col-sm-2 col-form-label">User Contact:</label>  
              <div class="col-sm-4">  
                {{ form.contact }}  
              </div>  
            </div>  
          
              <div class="form-group row">  
              <label class="col-sm-2 col-form-label">Gender:</label>      
              <div class="col-sm-4">  
                  {{ form.gender }}  
              </div>
            </div>    
              <div class="form-group row">  
              <label class="col-sm-2 col-form-label">Maritial Status:</label>      
              <div class="col-sm-4">  
                  {% for i in form.usrStatus %}
                  {{ i }}  
                  {% endfor %}
                  
              </div>
            </div>    
            <div class="form-group row">  
              <label class="col-sm-2 col-form-label">Age:</label>      
              <div class="col-sm-4">  
                  {{ form.age }}
              </div>
            </div>    
          
            <div class="form-group row">  
              <label class="col-sm-2 col-form-label">Date Of Journey:</label>      
              <div class="col-sm-4">  
                  {{ form.date_of_journey }}
              </div>
            </div>    
            <div class="form-group row">  
              <label class="col-sm-2 col-form-label">Seat:</label>      
              <div class="col-sm-4">  
                  {{ form.seat }}
              </div>
            </div>    
              <div class="form-group row">  
              <label class="col-sm-2 col-form-label">Coach:</label>      
              <div class="col-sm-4">  
                  {% for i in form.coach %}
                  {{ i }}
                  {% endfor %} 
                  
              </div>
            </div>    
            <div class="form-group row">  
              <label class="col-sm-2 col-form-label">Birthmark:</label>      
              <div class="col-sm-4">  
                  {{ form.birthmark }}
                  
              </div>
            </div>  
            <div class="form-group row">  
              <label class="col-sm-2 col-form-label">Image:</label>      
              <div class="col-sm-4">  
                  {{ form.usrImg }}
                  
              </div>
            </div>  
          
              <div class="form-group row">  
              <label class="col-sm-1 col-form-label"></label>  
              <div class="col-sm-4">  
              <button type="submit" class="btn btn-primary">Submit</button>  
              </div>  
            </div>  
              </div> 
</form> 
 
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>  
</html>  

Railway_Management /templates/read.html
{% load static %}

<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Booking Records</title>  
     {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
</head>  
<body>  
    <br><br><h2 align="center">Train Management Syatem</h2><br><br>

<table class="table table-striped table-bordered table-sm ">  
    <thead class="thead-dark">  
    <tr>  
        <th>ID</th>  
        <th>Name</th>  
        <th>Email</th>  
        <th>Contact</th>  
        <th>Gender</th>  
        <th>Maritial Status</th>  
        <th>Age</th>
        <th>DOJ</th>
        <th>Seat</th>
        <th>Vehicle</th>
        <th>Birthmark</th>
        <th>Image</th>
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for user in users %}  
    <tr>  
        <td>{{ user.id }}</td>  
        <td>{{ user.name }}</td>  
        <td>{{ user.email }}</td>  
        <td>{{ user.contact }}</td>  
        <td>{{ user.gender }}</td>  
        <td>{{ user.empStatus }}</td>  
        <td>{{ user.age }}</td>  
        <td>{{ user.date_of_join }}</td>  
        <td>{{ user.salary }}</td>  
        <td>{{ user.vehicle }}</td>  
        <td>{{ user.bio }}</td>  
        <td><img src="media/{{user.usrImg}}" alt="" width=50 height=50></td>
        <td>  
            <a href="/edit/{{ user.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ user.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/create" class="btn btn-primary">Book Now</a></center>  
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>  
</html>  

Railway_Management /templates/update.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Update</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{employee.id}}"  enctype="multipart/form-data">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Booking Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label"> Id:</label>  
    <div class="col-sm-4">  
        <input type="text" name="id" id="id_id" required maxlength="20" value="{{ user.id }}" disabled/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="name" id="id_name" required maxlength="100" value="{{ user.name }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Email:</label>  
    <div class="col-sm-4">  
        <input type="email" name="email" id="id_email" required maxlength="254" value="{{ user.email }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Contact:</label>  
    <div class="col-sm-4">  
        <input type="number" name="contact" id="id_contact" required maxlength="15" value="{{ user.contact }}" />  
    </div>  
  </div>
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Gender:</label>  
    <div class="col-sm-4">  
      <select name="gender" id="id_gender" selected="{{user.gender}}">
        <option selected value="{{user.gender}}">
          
        </option>
        <option value="M">Male</option>
      
        <option value="F">Female</option>
      
        <option value="O">Other</option>
      
        <option value="N" >None</option>
      
      </select>
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Maritial Status:</label>  
    <div class="col-sm-4">  
      <label for="id_usrStatus_0"><input type="radio" name="usrStatus" value="True" id="id_usrStatus_0">
        True</label>
      <label for="id_usrStatus_1"><input type="radio" name="usrStatus" value="False" id="id_usrStatus_1">
        False</label>
    </div>  
  </div>
  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Age:</label>  
    <div class="col-sm-4">  
      <input type="number" name="age" required id="id_age" value="{{ user.age }}">
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Date Of Journey:</label>  
    <div class="col-sm-4">  
      <input type="date" name="id_date_of_journey" class="form-control" id="id_date_of_journey" value="{{ user.date_of_journey }}">
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Seat:</label>  
    <div class="col-sm-4">  
      <input type="number" name="seat" step="any" required id="id_seat" value="{{ user.seat }}">
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Cauch:</label>  
    <div class="col-sm-4">  
      <label  for="id_cauch_0"><input type="checkbox" name="cauch" value="Car" id="id_cauch_0" >
 1st AC</label>
      <label for="id_cauch_1"><input type="checkbox" name="cauch" value="Bike" id="id_cauch_1">
 2nd AC</label>

<label for="id_cauch_2"><input type="checkbox" name="cauch" value="Cycle" id="id_cauch_2">
 3rd AC</label>

 <label for="id_cauch_3"><input type="checkbox" name="cauch" value="None" id="id_cauch_3">
 Sleeper</label>

    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Birthmark:</label>  
    <div class="col-sm-4">  
      <textarea name="birthmark" cols="30" rows="5" required id="id_birthmark">{{ user.birthmark }}</textarea>
    </div>  
  </div>
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Image:</label>  
    <div class="col-sm-4">  
      <input type="file" name="usrImg" accept="image/*" id="id_usrImg" value="{{ user.usrImg }}">
    </div>  
  </div>


    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>  
</html>